package com.kptest.domain.report.repository;

import com.kptest.domain.report.Report;
import com.kptest.domain.report.ReportType;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Repository interface for Report entity.
 */
@Repository
public interface ReportRepository extends JpaRepository<Report, UUID> {

    /**
     * Find reports by type.
     */
    List<Report> findByType(ReportType type);

    /**
     * Find reports by type and date range.
     */
    List<Report> findByTypeAndDateFromLessThanEqualAndDateToGreaterThanEqual(
        ReportType type, LocalDate dateFrom, LocalDate dateTo);

    /**
     * Find reports by project ID.
     */
    List<Report> findByProjectId(UUID projectId);

    /**
     * Find reports by patient ID.
     */
    List<Report> findByPatientId(UUID patientId);

    /**
     * Find reports by generated by user ID.
     */
    List<Report> findByGeneratedBy(UUID generatedBy);

    /**
     * Find reports by type and generated by.
     */
    List<Report> findByTypeAndGeneratedBy(ReportType type, UUID generatedBy);

    /**
     * Find latest report by type and project.
     */
    Optional<Report> findFirstByTypeAndProjectIdOrderByGeneratedAtDesc(ReportType type, UUID projectId);

    /**
     * Find latest report by type and patient.
     */
    Optional<Report> findFirstByTypeAndPatientIdOrderByGeneratedAtDesc(ReportType type, UUID patientId);

    /**
     * Count reports by type.
     */
    long countByType(ReportType type);

    /**
     * Find reports within date range.
     */
    @Query("SELECT r FROM Report r WHERE r.dateFrom <= :endDate AND r.dateTo >= :startDate")
    List<Report> findByDateRange(@Param("startDate") LocalDate startDate, @Param("endDate") LocalDate endDate);
}
